# Generated by Django 3.1.6 on 2021-02-10 08:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('wip', 'Work in progress'), ('done', 'Complete')], max_length=50)),
                ('exdate', models.DateTimeField(blank=True, null=True)),
                ('remarks', models.CharField(max_length=50)),
                ('reqno', models.CharField(max_length=50)),
                ('source', models.CharField(max_length=50)),
                ('ssubmit', models.CharField(choices=[('approved', 'Approve'), ('wip', 'Not approved')], max_length=50)),
                ('fapproval', models.CharField(max_length=50)),
                ('po_wo', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('createdon', models.DateTimeField(blank=True, null=True)),
                ('updatedon', models.DateTimeField(blank=True, null=True)),
                ('compid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='department.company')),
                ('createdby', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_who_create', to=settings.AUTH_USER_MODEL)),
                ('deptid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='department.department')),
                ('updatedby', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_who_update', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyDeptUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='department.company')),
                ('deptid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='department.department')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyDept',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='department.company')),
                ('deptid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='department.department')),
            ],
        ),
    ]
